version: '3.2'

services:
  secim_tutanak_ocr_api:
    build: .
    container_name: secim_tutanak_ocr_api
    restart: always
    volumes:
      - .:/code/

    command: 'uvicorn secim_tutanak_ocr_api.main:app --reload --host 0.0.0.0 --port 8080'
    env_file:
      - .env
    ports:
      - 8080:8080

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

      

